import os
import smtplib
import re
import time
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# ====================================================
# 🟢 FINAL CONFIGURATION: THE "GUARANTEE" SCRIPT
# ====================================================
LOGIN_URL = "https://nietcloud.niet.co.in/login.htm"
# ⚠️ CORRECTED URL FROM YOUR SCREENSHOT (2700A)
DETAILED_URL = "https://nietcloud.niet.co.in/studentCourseFileNew.htm?shwA=%272700A%27"

USER_BOX_ID = "j_username"
PASS_BOX_ID = "password-1"
LOGIN_BTN_SELECTOR = "button[type='submit']"

COLLEGE_USER = os.environ["COLLEGE_USER"]
COLLEGE_PASS = os.environ["COLLEGE_PASS"]
SENDER_EMAIL = os.environ["EMAIL_USER"]
SENDER_PASS  = os.environ["EMAIL_PASS"]
TARGET_EMAIL = os.environ["TARGET_EMAIL"]

def send_email(percentage_text, fraction_text, status_msg):
    msg = MIMEMultipart("alternative")
    
    # Color Logic
    try:
        val = float(re.search(r'\d+\.?\d*', percentage_text).group())
        color = "red" if val < 75 else "green"
        alert = "🚨 LOW ATTENDANCE" if val < 75 else "✅ SAFE ZONE"
    except:
        color = "blue"
        alert = "📅 DAILY UPDATE"

    msg['Subject'] = f"{alert}: {percentage_text} ({fraction_text})"
    msg['From'] = SENDER_EMAIL
    msg['To'] = TARGET_EMAIL

    html = f"""
    <html>
      <body style="font-family: Helvetica, sans-serif; background-color: #f0f0f0; padding: 20px;">
        <div style="background-color: white; border-top: 5px solid {color}; padding: 20px; border-radius: 5px;">
            <h2 style="color: {color}; margin-top:0;">{alert}</h2>
            <table style="width: 100%; margin-top: 10px;">
                <tr>
                    <td><strong>Total Percentage:</strong></td>
                    <td style="font-size: 22px; color: {color};"><strong>{percentage_text}</strong></td>
                </tr>
                <tr>
                    <td><strong>Classes Attended:</strong></td>
                    <td style="font-size: 18px;">{fraction_text}</td>
                </tr>
            </table>
            <hr style="margin: 20px 0; border: 0; border-top: 1px solid #eee;">
            <p style="font-size: 11px; color: #666;">
                <b>Bot Status:</b> {status_msg}<br>
                <i>Auto-generated by GitHub Actions</i>
            </p>
        </div>
      </body>
    </html>
    """
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(SENDER_EMAIL, SENDER_PASS)
            server.sendmail(SENDER_EMAIL, TARGET_EMAIL, msg.as_string())
        print("✅ EMAIL SENT SUCCESSFULLY!")
    except Exception as e:
        print(f"❌ EMAIL FAILED: {e}")

def main():
    chrome_options = Options()
    chrome_options.add_argument("--headless")
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_options.add_argument('--ignore-certificate-errors')
    
    driver = webdriver.Chrome(options=chrome_options)
    wait = WebDriverWait(driver, 30)

    # Placeholders
    final_percent = "N/A"
    final_fraction = "N/A"
    log_status = "Init"

    try:
        print("🚀 Opening NIET Cloud...")
        driver.get(LOGIN_URL)
        
        # 1. Login
        wait.until(EC.visibility_of_element_located((By.ID, USER_BOX_ID))).send_keys(COLLEGE_USER)
        driver.find_element(By.ID, PASS_BOX_ID).send_keys(COLLEGE_PASS)
        driver.find_element(By.CSS_SELECTOR, LOGIN_BTN_SELECTOR).click()
        print("🔓 Login Clicked...")
        
        # 2. Grab Dashboard Data (BACKUP PLAN)
        # We grab the 45.65% from the home screen immediately, just in case everything else fails.
        wait.until(EC.text_to_be_present_in_element((By.TAG_NAME, "body"), "Attendance"))
        dashboard_text = driver.find_element(By.TAG_NAME, "body").text
        
        dash_matches = re.findall(r'(\d+\.\d+)%', dashboard_text)
        if dash_matches:
            final_percent = dash_matches[-1] + "%" # Grab the last percentage seen
            log_status = "Dashboard Data Only (Detailed View Failed)"
            print(f"💾 Backup Data Secured: {final_percent}")

        # 3. Teleport to Detailed View
        print(f"🚀 Teleporting to: {DETAILED_URL}")
        driver.get(DETAILED_URL)
        
        # 4. Wait for Table
        try:
            wait.until(EC.presence_of_element_located((By.XPATH, "//tr[last()]/td[last()]")))
            print("⏳ Detailed Table Loaded.")
            
            # 5. Extract Data
            # Percentage is in the last cell of the last row
            p_el = driver.find_element(By.XPATH, "//tr[last()]/td[last()]")
            # Fraction is in the cell before it
            f_el = driver.find_element(By.XPATH, "//tr[last()]/td[last()-1]")
            
            if p_el.text.strip():
                final_percent = p_el.text.strip()
                final_fraction = f_el.text.strip()
                log_status = "Full Detailed Data Success"
                print(f"🎯 SUCCESS: {final_percent} | {final_fraction}")
            else:
                print("⚠️ Table found but cells were empty.")
                
        except Exception as table_err:
            print(f"⚠️ Could not load detailed table: {table_err}")
            print("➡️ Reverting to Dashboard Backup Data.")

        # 6. Send Email (Guaranteed)
        if final_percent != "N/A":
            send_email(final_percent, final_fraction, log_status)
        else:
            print("❌ CRITICAL: No data found on Dashboard OR Detailed page.")

    except Exception as e:
        print(f"❌ Script Crash: {e}")
    
    finally:
        driver.quit()

if __name__ == "__main__":
    main()
